// Generated by eosio-abi2ts 1.2.1 - eosio::abi/1.1

export type BlogFlags = Uint8
export type Asset = string
export type Name = string
export type Checksum256 = string
export type TimePointSec = string
export type Uint8 = number
export type Uint16 = number
export type Uint32 = number
export type Uint64 = number | string
export type LinkFlags = Uint8
export type PostOptions = Uint8
export type VariantPlaceholder = ['color', Color] | ['geometrize_triangles', GeometrizeTriangles]
export type VariantMarkNodes = ['link', Link] | ['bold', Bold] | ['italic', Italic] | ['code', Code] | ['strike', Strike]
export type VariantBlockNodes = ['paragraph', Paragraph] | ['heading', Heading] | ['image', Image] | ['linkref', Linkref] | ['quote', Quote] | ['code_block', CodeBlock] | ['divider', Divider] | ['list', List]
export type VariantInlineNodes = ['text', Text] | ['hard_break', HardBreak]
export interface ActionAddcategory {
    category: Name
}
export interface ActionAddmoderator {
    account: Name
}
export interface ActionCreateblog {
    author: Name
}
export interface ActionDelcategory {
    category: Name
}
export interface ActionDeleteblog {
    author: Name
    max_itr: Uint32
}
export interface ActionDelmoderator {
    account: Name
}
export interface ActionFreezeblog {
    author: Name
    reason: string
}
export interface ActionHousekeeping {
    max_itr: Uint32
}
export interface ActionPinpost {
    author: Name
    slug: Name
}
export interface ActionPost {
    author: Name
    title: string
    doc: Document
    metadata?: Metadata
}
export interface ActionPostedit {
    author: Name
    new_title?: string
    patch?: string
    new_metadata?: Metadata
}
export interface ActionProfile {
    author: Name
    name: string
    bio: string
    image?: string
}
export interface ActionPublish {
    permlink: Permlink
    tx: TxRef
    category: Name
    options: PostOptions
    links: Permlink[]
}
export interface ActionPublishedit {
    permlink: Permlink
    edit_tx: TxRef
}
export interface ActionSetlinkflags {
    link_id: Uint64
    new_flags: LinkFlags
}
export interface ActionSetprofile {
    author: Name
    profile: TxRef
}
export interface ActionUnfreezeblog {
    author: Name
}
export interface ActionUnpinpost {
    author: Name
    slug: Name
}
export interface ActionUnpublish {
    permlink: Permlink
}
export interface ActionUpdatescore {
    post_permlink: Permlink
}
export interface BlogRow {
    author: Name
    flags: BlogFlags
    pinned: Name[]
    stats: BlogStats
    profile?: TxRef
    extensions: FutureExtensions[]
}
export interface BlogStats {
    total_posts: Uint32
    endorsements_received: RewardStat
    endorsements_sent: RewardStat
    incoming_linkbacks: RewardStat
    outgoing_linkbacks: RewardStat
}
export interface Bold {
}
export interface CategoryStat {
    endorsements: RewardStat
    linkbacks: RewardStat
}
export interface Code {
}
export interface CodeBlock {
    code: string
    lang: string
}
export interface Color {
    r: Uint8
    g: Uint8
    b: Uint8
}
export interface Divider {
}
export interface Document {
    content: VariantBlockNodes[]
}
export interface FutureExtensions {
}
export interface GeometrizeTriangles {
    base: Color
    triangles: Triangle[]
}
export interface HardBreak {
}
export interface Heading {
    value: string
    level: Uint8
}
export interface Image {
    src: string
    caption: VariantInlineNodes[]
    layout: Uint8
}
export interface ImageInfo {
    width: Uint16
    height: Uint16
    placeholder: VariantPlaceholder
}
export interface Italic {
}
export interface Link {
    href: string
    title: string
}
export interface LinkRow {
    id: Uint64
    from: Permlink
    to: Permlink
    flags: LinkFlags
    payment?: Asset
}
export interface Linkref {
    to: Permlink
}
export interface List {
    type: Uint8
    items: ListItem[]
}
export interface ListItem {
    content: VariantInlineNodes[]
}
export interface Metadata {
    image?: string
    summary?: string
    image_info: PairStringImageInfo[]
}
export interface PairNameCategoryStat {
    key: Name
    value: CategoryStat
}
export interface PairStringImageInfo {
    key: string
    value: ImageInfo
}
export interface Paragraph {
    content: VariantInlineNodes[]
}
export interface Permlink {
    author: Name
    slug: Name
}
export interface PostRef {
    permlink: Permlink
    timestamp: TimePointSec
    category: Name
    options: PostOptions
    tx: TxRef
    edit_tx?: TxRef
    endorsements?: RewardStat
    extensions: FutureExtensions[]
}
export interface PostRow {
    ref: PostRef
    extensions: FutureExtensions[]
}
export interface Quote {
    content: VariantInlineNodes[]
}
export interface RewardStat {
    count: Uint32
    amount: Uint64
}
export interface State {
    moderators: Name[]
    categories: PairNameCategoryStat[]
}
export interface Strike {
}
export interface Text {
    value: string
    marks: VariantMarkNodes[]
}
export interface TrendingRow {
    id: Uint64
    score: Uint64
    ref: PostRef
    extensions: FutureExtensions[]
}
export interface Triangle {
    ax: Uint8
    ay: Uint8
    bx: Uint8
    by: Uint8
    cx: Uint8
    cy: Uint8
    color: Color
}
export interface TxRef {
    block_num: Uint32
    transaction_id: Checksum256
}
